language: android
sudo: false

android:
  components:
  - build-tools-27.0.1
  - android-27
env:
  global:
  # Keep gradle from crapping all over the log
  - TERM=dumb
  - NODE_VERSION=8

branches:
  only:
  - master

before_install:
  - nvm install $NODE_VERSION
  - npm install -g cordova

install:
- npm install

before_script:
- cordova platform rm android
- cordova platform add android

script:
- npm run build
- cordova prepare
- cordova build android --release -- --ant

release:
- exit 0
