language: android
sudo: false

jdk:
- oraclejdk8

android:
  components:
  - build-tools-26.0.2
env:
  global:
  # Keep gradle from crapping all over the log
  - TERM=dumb
  matrix:
  - nodejs_version=8

branches:
  only:
  - master

install:
- yes | sdkmanager tools > /dev/null
- yes | sdkmanager --licenses > /dev/null

- nvm install $nodejs_version
- npm install
- npm install -g cordova
- echo y | android update sdk -u --filter android-22,android-23

before_script:
- cordova platform rm android
- cordova platform add android

script:
- gradle --version
- node --version
- npm --version
- npm run build
- cordova prepare
- cordova build android --release -- --ant

release:
- exit 0
