language: android
sudo: false
before_deploy:
- cp $TRAVIS_BUILD_DIR/padmiss.keystore $HOME
- cd platforms/android/app/build/outputs/apk/release/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/padmiss.keystore
  -storepass $storepass -keypass $storepass app-release-unsigned.apk padmiss
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/26.0.2/zipalign -v 4 app-release-unsigned.apk padmiss.apk"
- git config --local user.name "Electromuis"
- git config --local user.email "anton.grootes11@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OWoYIr5FHdMQOIBd4TmbeHFpQ2B/BxSBYzWgXcnTupCaPHSUgLfmMqOj8yi4d8WSS+dB1wDxkxuJ7DFVozmrav60fMehFbO4qgAqH/UttIHy3BbVoj1jT/AQuwU8IcNXwwI3oO12vPqLcpsCBeStPij1NToo6g7eSU7YpCTZDSrWKlPVjW0l537n0m12VQ2B+xlnzUD8gFdcPZ8OnOnqPbemWCu0hdWenrlVe7Dnj14h8/SPARvpSF/t+j7egiczg6r5DvJszHNq36+FO7k8Q06bS9b41DoZMxpLWiIPinCBzy0c8VQt6az97X/CpsqSTHVIKNt77ydHp/dvR2VRx87R7wR+vNEu4t6HeQElNNzRju9B7CovvxagttCtd9BDZLQ9WwVsrCjPGCfIAks01WOVVe8F+EI1xxRcxN5peihMuwFVZhGR6MqYNGl0IfGxvOPaDtxKvmMhClhcxg+iwPIz92yer+ukTAVA8PTNEoPvUvNRSa2o0rZ84l7+zsaZJ4flrAn9mL/KRpU/F3TWpIUCTLWn2YS34WiuHuJ2QjE52fh6DjO5alceI+VS8pgEL4Jnbpmr1eeCrhrbP729NqqJu8lEn7YgXpNJNn6npa9qWU2F28v67Ek2Cg3/9XrHSTTDgLWY3pJ4nq/oELPqq9qRTtbGHVoZ/E9KDXLVHZk=
  file: padmiss.apk
  file_glob: 'true'
  on:
    repo: electromuis/padmiss-app
android:
  components:
  - build-tools-27.0.1
  - android-27
  - build-tools-26.0.2
  - android-26
env:
  global:
  - TERM=dumb
  - NODE_VERSION=8
  - secure: IN8Kc7boWqsFypsWnhZxC9FZm7bQzV0+1Iov+K6i5+mypG9YSZa/Q2HWmzKdRJ3xYuE1cWXSY5e3RlgkahvbiWgjsQUhTVGHOAsYfehsoo18LT+veOj4EpMFLwpivmegh8Dj9jeJKYAN4wx0Y8uxzHqWYkPxcrMdlcnvwomDSrg07naG3KFpEUCnJX3rrW42q0z9yBo+Rrt1huNSr519KTAXjqHp4Ig/tAd9CsDpP9R0fAhk6ydBjum1OCZT5Gxtf/JBPcUHQja1rmvdZFAeNx81y3SVf8mKENsX5cdgi/17keM4OrIghbD+bvcUaLssQCiXVRYnrVzU1xhU7uTrOl0mZ/M38nf3mvghSEh5hDvOri2pcExjXShuFzjr31wSskb4JxVjnmoaI2SHJ4vp7I5k5OEgjSeZaQByHVK94pnLRgnXwHjXAs2odjpmR8pbE8YW1qJPx6cb3PH/TzM0mix3PPJV+oZJqfGtnXyukbfGqTV9l153jIz6powUYEA7f8XFWkRPCRxboag22FKTCpxpJHvcdbDjruMJulneuFB5bUHWkkqyi8YlsqizeMJyc8J7xqi1c3+q4OgfMnc1KtHKQUlydo89AxOVKc5HMNa4PVbRSuoZNBsP3AjM73LOJNS50wwgR4LmT5ecjwIJlkmpECgNLkbMz+8pbU7klns=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_cef1a47cec93_key -iv $encrypted_cef1a47cec93_iv
  -in padmiss.keystore.enc -out padmiss.keystore -d
- nvm install $NODE_VERSION
- npm install -g cordova
install:
- npm install
before_script:
- cordova platform rm android
- cordova platform add android
script:
- npm run build
- cordova prepare
- cordova build android --release -- --ant
release:
- exit 0
