language: android
sudo: false

before_deploy:
# Set up git user name and tag this commit
- git config --local user.name "Electromuis"
- git config --local user.email "anton.grootes11@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk"
  skip_cleanup: true

android:
  components:
  - build-tools-27.0.1
  - android-27
env:
  global:
  # Keep gradle from crapping all over the log
  - TERM=dumb
  - NODE_VERSION=8

branches:
  only:
  - master

before_install:
  - nvm install $NODE_VERSION
  - npm install -g cordova

install:
- npm install

before_script:
- cordova platform rm android
- cordova platform add android

script:
- npm run build
- cordova prepare
- cordova build android --release -- --ant

release:
- exit 0
